// Package po reads and writes gettext PO files: the subset translation
// tools such as Poedit produce for singular messages.
//
// Supported: the header entry, translator comments ("# "), extracted
// comments ("#."), references ("#:"), flags ("#,"), msgctxt, multi-line
// strings and obsolete entries ("#~"). Plural forms are rejected.
package po

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"slices"
	"strconv"
	"strings"
)

// ErrFormat reports malformed PO content.
var ErrFormat = errors.New("po: malformed file")

// Message is one PO entry.
type Message struct {
	// Comments are translator comments, Extracted the comments a tool
	// generated for translators, References the source locations.
	Comments   []string
	Extracted  []string
	References []string
	Flags      []string
	Context    string
	ID         string
	Str        string
	// Obsolete marks an entry kept only to preserve its translation.
	Obsolete bool
}

// Fuzzy reports whether the translation is marked as needing review.
// Gettext does not use fuzzy translations.
func (m Message) Fuzzy() bool { return slices.Contains(m.Flags, "fuzzy") }

// File is the content of a PO file. Header is the entry with an empty
// msgid; its Str holds the header fields.
type File struct {
	Header   Message
	Messages []Message
}

// Parse decodes PO content.
func Parse(data []byte) (*File, error) {
	p := parser{f: &File{}}
	sc := bufio.NewScanner(bytes.NewReader(data))
	sc.Buffer(nil, 64<<20)
	for sc.Scan() {
		p.line++
		if err := p.parseLine(strings.TrimSpace(sc.Text())); err != nil {
			return nil, fmt.Errorf("%w: line %d: %w", ErrFormat, p.line, err)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrFormat, err)
	}
	if err := p.flush(); err != nil {
		return nil, fmt.Errorf("%w: line %d: %w", ErrFormat, p.line, err)
	}
	return p.f, nil
}

type parser struct {
	f    *File
	line int
	cur  Message
	// field is the keyword the next continuation string belongs to.
	field string
	// hasID is set once the current entry has a msgid.
	hasID, hasStr bool
	header        bool
}

func (p *parser) parseLine(line string) error {
	obsolete := false
	if rest, ok := strings.CutPrefix(line, "#~"); ok {
		obsolete = true
		line = strings.TrimSpace(rest)
		if line == "" || strings.HasPrefix(line, "|") {
			return nil
		}
	}
	switch {
	case line == "":
		return p.flush()
	case strings.HasPrefix(line, "#"):
		if p.hasStr {
			if err := p.flush(); err != nil {
				return err
			}
		}
		p.comment(line)
		return nil
	case strings.HasPrefix(line, `"`):
		if p.field == "" {
			return errors.New("string without a keyword")
		}
		s, err := unquote(line)
		if err != nil {
			return err
		}
		p.appendTo(p.field, s)
		return nil
	}
	keyword, rest, _ := strings.Cut(line, " ")
	value, err := unquote(strings.TrimSpace(rest))
	if err != nil {
		return err
	}
	switch keyword {
	case "msgctxt", "msgid":
		if p.hasStr || (keyword == "msgctxt" && p.hasID) {
			if err := p.flush(); err != nil {
				return err
			}
		}
		if keyword == "msgid" {
			if p.hasID {
				return errors.New("msgid repeated before msgstr")
			}
			p.hasID = true
		}
	case "msgstr":
		if !p.hasID || p.hasStr {
			return errors.New("msgstr without msgid")
		}
		p.hasStr = true
	case "msgid_plural", "msgstr[0]", "msgstr[1]", "msgstr[2]":
		return errors.New("plural forms are not supported")
	default:
		return fmt.Errorf("unknown keyword %q", keyword)
	}
	p.cur.Obsolete = p.cur.Obsolete || obsolete
	p.field = keyword
	p.appendTo(keyword, value)
	return nil
}

func (p *parser) comment(line string) {
	kind, text := line[:min(len(line), 2)], strings.TrimSpace(line[min(len(line), 2):])
	switch kind {
	case "#.":
		p.cur.Extracted = append(p.cur.Extracted, text)
	case "#:":
		p.cur.References = append(p.cur.References, strings.Fields(text)...)
	case "#,":
		for f := range strings.SplitSeq(text, ",") {
			if f = strings.TrimSpace(f); f != "" {
				p.cur.Flags = append(p.cur.Flags, f)
			}
		}
	case "#|":
		// Previous msgid of a fuzzy entry: regenerated by tools, not kept.
	default:
		p.cur.Comments = append(p.cur.Comments, strings.TrimSpace(line[1:]))
	}
}

func (p *parser) appendTo(field, s string) {
	switch field {
	case "msgctxt":
		p.cur.Context += s
	case "msgid":
		p.cur.ID += s
	case "msgstr":
		p.cur.Str += s
	}
}

func (p *parser) flush() error {
	defer func() { p.cur, p.field, p.hasID, p.hasStr = Message{}, "", false, false }()
	switch {
	case !p.hasID && !p.hasStr:
		if len(p.cur.Comments)+len(p.cur.Extracted)+len(p.cur.References)+len(p.cur.Flags) > 0 {
			return errors.New("comments without an entry")
		}
		return nil
	case !p.hasStr:
		return errors.New("msgid without msgstr")
	case p.cur.ID == "" && p.cur.Context == "" && !p.cur.Obsolete:
		if p.header || len(p.f.Messages) > 0 {
			return errors.New("header entry must come first")
		}
		p.f.Header, p.header = p.cur, true
		return nil
	}
	p.f.Messages = append(p.f.Messages, p.cur)
	return nil
}

// unquote decodes a C-style PO string literal.
func unquote(s string) (string, error) {
	if len(s) < 2 || s[0] != '"' || s[len(s)-1] != '"' {
		return "", fmt.Errorf("expected a quoted string, got %q", s)
	}
	body := s[1 : len(s)-1]
	var b strings.Builder
	for i := 0; i < len(body); i++ {
		c := body[i]
		if c == '"' {
			return "", errors.New("unescaped quote in string")
		}
		if c != '\\' {
			b.WriteByte(c)
			continue
		}
		i++
		if i == len(body) {
			return "", errors.New("string ends with a backslash")
		}
		switch e := body[i]; e {
		case 'n':
			b.WriteByte('\n')
		case 't':
			b.WriteByte('\t')
		case 'r':
			b.WriteByte('\r')
		case 'a':
			b.WriteByte('\a')
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'v':
			b.WriteByte('\v')
		case '\\', '"', '\'', '?':
			b.WriteByte(e)
		case 'x':
			j := i + 1
			for j < len(body) && j < i+3 && isHex(body[j]) {
				j++
			}
			if j == i+1 {
				return "", errors.New(`\x without hex digits`)
			}
			n, _ := strconv.ParseUint(body[i+1:j], 16, 8)
			b.WriteByte(byte(n))
			i = j - 1
		case '0', '1', '2', '3', '4', '5', '6', '7':
			j := i
			for j < len(body) && j < i+3 && body[j] >= '0' && body[j] <= '7' {
				j++
			}
			n, err := strconv.ParseUint(body[i:j], 8, 8)
			if err != nil {
				return "", fmt.Errorf("octal escape: %w", err)
			}
			b.WriteByte(byte(n))
			i = j - 1
		default:
			return "", fmt.Errorf("unknown escape \\%c", e)
		}
	}
	return b.String(), nil
}

func isHex(c byte) bool {
	return c >= '0' && c <= '9' || c >= 'a' && c <= 'f' || c >= 'A' && c <= 'F'
}

// Marshal encodes f. Strings with line breaks are split after each break,
// as gettext tools do.
func Marshal(f *File) []byte {
	var b bytes.Buffer
	writeComments(&b, f.Header)
	writeString(&b, "", "msgid", "")
	writeString(&b, "", "msgstr", f.Header.Str)
	for _, m := range f.Messages {
		b.WriteByte('\n')
		prefix := ""
		if m.Obsolete {
			prefix = "#~ "
		}
		writeComments(&b, m)
		if m.Context != "" {
			writeString(&b, prefix, "msgctxt", m.Context)
		}
		writeString(&b, prefix, "msgid", m.ID)
		writeString(&b, prefix, "msgstr", m.Str)
	}
	return b.Bytes()
}

// writeComments writes the comment lines of m. Comments of obsolete
// entries stay plain comments, as msgmerge writes them.
func writeComments(b *bytes.Buffer, m Message) {
	for _, c := range m.Comments {
		b.WriteString(strings.TrimRight("# "+c, " ") + "\n")
	}
	for _, c := range m.Extracted {
		b.WriteString(strings.TrimRight("#. "+c, " ") + "\n")
	}
	if len(m.References) > 0 {
		b.WriteString("#: " + strings.Join(m.References, " ") + "\n")
	}
	if len(m.Flags) > 0 {
		b.WriteString("#, " + strings.Join(m.Flags, ", ") + "\n")
	}
}

func writeString(b *bytes.Buffer, prefix, keyword, s string) {
	lines := strings.SplitAfter(s, "\n")
	if lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	if len(lines) <= 1 {
		fmt.Fprintf(b, "%s%s %s\n", prefix, keyword, quote(s))
		return
	}
	fmt.Fprintf(b, "%s%s \"\"\n", prefix, keyword)
	for _, l := range lines {
		fmt.Fprintf(b, "%s%s\n", prefix, quote(l))
	}
}

func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		case '\a':
			b.WriteString(`\a`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		case '\v':
			b.WriteString(`\v`)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\%03o`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
